### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Sin-Sumit** [chandrikadeb7/Hacktoberfest_2021#348]
Having Issue Templates makes it easy to report a bug, feature, or documentation for both contributor & maintainer.
Like for Task1 Task2 Task3, adding an issue before starting any PR.

**Comment by Sin-Sumit** [comment]
@chandrikadeb7 I'd like to add them. Please assign me.

**Comment by nimishbongale** [comment]
@Sin-Sumit you can contribute to the repo without having the need to raise an issue. Thanks!
